language: cpp
os: linux
dist: focal

compiler:
  - gcc
  - clang

env:
  - CMAKE_BUILD_TYPE=Release LLVM_VER=
  - CMAKE_BUILD_TYPE=Release LLVM_VER=10
  - CMAKE_BUILD_TYPE=Release LLVM_VER=11
  - CMAKE_BUILD_TYPE=Debug LLVM_VER=
  - CMAKE_BUILD_TYPE=Debug LLVM_VER=10
  - CMAKE_BUILD_TYPE=Debug LLVM_VER=11

addons:
  apt:
    packages:
      - libopenlibm-dev
      - libsleef-dev
      - libzmq3-dev

before_script:
  - if [ -n "${LLVM_VER}" ]; then sudo apt-get install llvm-${LLVM_VER}-dev; fi

script:
  - bash -e test/travis_build.sh
  - cd build && ctest -E /excluded -j $(nproc) --output-on-failure
