name: ArchLinux

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CXXFLAGS_COV: -fprofile-arcs -ftest-coverage

jobs:
  build:
    name: "${{matrix.BUILD_TYPE}} build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: [ Release, Debug ]
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Install git
        run: |
          pacman-key --init
          pacman-key --populate archlinux

          pacman -Syu --noconfirm git
      - uses: actions/checkout@v4
      - name: Initialize ArchLinux
        run: |
          bash github/setup-archlinux.sh
          chown -R user .
      - name: Setup ArchLinux CN repo
        # For sleef
        run: |
          bash github/setup-archlinux-cn.sh
      - name: Install dependencies
        run: pacman -S --noconfirm cmake intel-tbb llvm openlibm sleef yaml-cpp zeromq cppzmq

      - name: Configure CMake
        run: CXXFLAGS+=" ${CXXFLAGS_COV}" cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DENABLE_SIMD=On -DENABLE_LLVM=On

      - name: Build
        run: cmake --build build --config ${{matrix.BUILD_TYPE}} -j $(nproc)

      - name: Builder info
        run: build/tools/nacs-cpudump

      - name: Test
        working-directory: build
        run: ctest -C ${{matrix.BUILD_TYPE}} -E /excluded --output-on-failure -j $(nproc)

      - name: Generate coverage report
        run: |
          find build/{lib,tools} -iname '*.o' -exec gcov -abcfupr {} -s ${PWD} \;

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
