name: Linux

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: [ Release, Debug ]
        compiler: [ gcc, clang ]
        LLVM_VER: [ '', 11 ]
        ENABLE_SIMD: [ On ]
        exclude:
          - BUILD_TYPE: Release
            compiler: clang
            LLVM_VER: ''
            ENABLE_SIMD: On
          - BUILD_TYPE: Debug
            compiler: clang
            LLVM_VER: ''
            ENABLE_SIMD: On
        include:
          - BUILD_TYPE: Debug
            compiler: gcc
            LLVM_VER: 10
            ENABLE_SIMD: On
          - BUILD_TYPE: Debug
            compiler: gcc
            LLVM_VER: 11
            ENABLE_SIMD: Off
    env:
      CC: ${{matrix.compiler}}
      CXX: ${{matrix.compiler == 'gcc' && 'g++' || 'clang++'}}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libopenlibm-dev libsleef-dev libzmq3-dev libyaml-cpp-dev libtbb-dev

    - name: Install LLVM
      if: ${{matrix.LLVM_VER != ''}}
      run: sudo apt-get install llvm-${{matrix.LLVM_VER}}-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DENABLE_SIMD=${{matrix.ENABLE_SIMD}} -DENABLE_LLVM=${{matrix.LLVM_VER != '' && 'On' || 'Off'}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.BUILD_TYPE}} -E /excluded --output-on-failure -j $(nproc)
